Set WshShell = createobject("wscript.Shell")

WScript.Sleep 2000

Do
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
WScript.Sleep 1000
WshShell.SendKeys "SPAM"
WshShell.SendKeys "~"
x=Msgbox("End Spam",4, "End Spam")
if x=6 then WScript.Quit 1
Loop





